#############
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robert Hosking
email: roberthosking96@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Millennial who loves technology, self improvement, and adventure. 
  I'm a developer, designer, writer, and entrepreneur looking to add value to the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://roberthosking.com" # the base hostname & protocol for your site
twitter: robhossboss
github:  robhossboss
instagram: robert_hosking

# Build settings
markdown: kramdown
